name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with Black
        run: |
          black . --check -l 120
      - name: Test with unittest
        env:
          TG_TEST_ID: ${{ secrets.TG_TEST_ID }}
          TG_TEST_HASH: ${{ secrets.TG_TEST_HASH }}
          TELEGRAM_TEST_SESSION: ${{ secrets.TELEGRAM_TEST_SESSION }}
        run: |
          if [ -d tests ]; then python -m pytest tests; fi
      - name: Check types with mypy
        run: |
          if [ -d src ]; then mypy src --ignore-missing-imports; fi
